﻿(function(){
const PRODUCTS=[
{id:'asthin-force-6',name:'Asthin Force 6 Quidfast',division:'Digital OTC',category:'Immune Support',image:'asthin force 6 quidfast.webp',imageAlt:'Asthin Force 6 Quidfast softgels',summary:'Astaxanthin softgel that fights free radicals and supports daily immunity.',benefits:['Powerful antioxidant blend for daily defense.','Ideal companion for active adults and commuters.'],directions:['Take one softgel after meals or as advised by your doctor.','Consult a physician if you are pregnant, lactating, or on long-term medication.'],availability:'Available in Mercury Drug, Watsons, South Star Drug, and Britton partner outlets nationwide.',tags:['immune','antioxidant','supplement']},
{id:'blite',name:'BLITE',division:'Digital OTC',category:'Weight Management',image:'BLITE.webp',imageAlt:'BLITE herbal capsule',summary:'Herbal capsule that helps support healthy weight goals alongside diet and exercise.',benefits:['Contains botanical ingredients that help manage cravings and metabolism.','Simple once or twice daily capsule for on-the-go adults.'],directions:['Take one capsule twice daily after meals or as advised by your healthcare professional.','Use with balanced meals, hydration, and regular physical activity.'],availability:'Available via leading pharmacies, wellness retailers, and Britton-authorized ecommerce partners.',tags:['weight','herbal','wellness']},
{id:'hepanorm',name:'Hepanorm',division:'Digital OTC',category:'Liver Health',image:'hepanorm 1.webp',imageAlt:'Hepanorm liver support capsule',summary:'Liver-support supplement with silymarin and antioxidants for everyday detox support.',benefits:['Assists the liver in flushing out toxins from daily stress.','Provides antioxidants that help protect hepatic cells.'],directions:['Take one capsule once or twice daily after meals or according to your physician.','Avoid excessive alcohol intake and consult your doctor for prolonged use.'],availability:'Stocked by pharmacies nationwide and distributed by Britton provincial teams.',tags:['liver','silymarin','detox']},
{id:'imboost-caplet',name:'Imboost Caplet',division:'Digital OTC',category:'Immunity',image:'imboost caplet 1.webp',imageAlt:'Imboost caplet blister pack',summary:'Echinacea and zinc caplet that reinforces adult immunity during high-risk seasons.',benefits:['Helps activate immune response with trusted Echinacea extract.','Convenient twice-daily format for busy professionals.'],directions:['Adults may take one caplet twice daily or as directed by a healthcare professional.','Best paired with adequate sleep, hydration, and balanced meals.'],availability:'Stocked by leading pharmacies nationwide and official Britton online stores.',tags:['echinacea','zinc','immune']},
{id:'imboost-syrup',name:'Imboost Syrup',division:'Division 1 – Pedia / Derma / OB',category:'Pediatric Immunity',image:'imboost syrup 1.webp',imageAlt:'Imboost syrup bottle',summary:'Pleasant-tasting immunity syrup for kids fortified with Echinacea and zinc.',benefits:['Supports natural defenses during school season and weather changes.','Kid-friendly formula trusted by pediatricians.'],directions:['Follow pediatric dosage based on age and doctor’s advice.','Shake well before use and store tightly capped in a cool place.'],availability:'Available through pediatric clinics, Mercury Drug, South Star Drug, and Britton provincial distributors.',tags:['children','immune','syrup']},
{id:'lindell-30',name:'Lindell Cough Syrup 30 mL',division:'Division 1 – Pedia / Derma / OB',category:'Respiratory Care',image:'lindell 30ml.webp',imageAlt:'Lindell cough syrup 30 mL',summary:'Expectorant syrup that helps loosen phlegm and ease troublesome cough for kids.',benefits:['Provides soothing relief from throat irritation and stubborn phlegm.','Gentle formulation crafted for pediatric patients.'],directions:['Consult your pediatrician for the appropriate dose by age or weight.','Do not exceed seven days of use unless advised by a doctor.'],availability:'Distributed to pediatric clinics, partner hospitals, and major community pharmacies.',tags:['cough','pediatric','expectorant']},
{id:'primo-grow',name:'Primo Grow Syrup',division:'Division 1 - Pedia / Derma / OB',category:'Growth & Nutrition',image:'primo grow.webp',imageAlt:'Primo Grow syrup bottle',summary:'Multivitamin with lysine that helps picky eaters develop healthy appetite and growth.',benefits:['Delivers essential vitamins that support growth milestones.','Great-tasting syrup that encourages daily compliance.'],directions:['Administer the prescribed dose using the enclosed spoon after meals.','Pair with balanced meals and regular wellness checkups.'],availability:'Supplied by Britton sales teams to pediatric clinics, hospitals, and retail chains.',tags:['multivitamin','children','appetite']},
{id:'memoking',name:'Memoking',division:'Digital OTC',category:'Cognitive Support',image:'memoking 1.webp',imageAlt:'Memoking cognitive support supplement',summary:'Ginkgo biloba-based supplement that aids memory, focus, and mental stamina.',benefits:['Supports healthy circulation to the brain for sharper cognition.','Combines antioxidants that help protect nerve cells from stress.'],directions:['Adults may take one capsule daily with meals or as directed by a healthcare professional.','Not recommended for pregnant women or patients on blood thinners without medical guidance.'],availability:'Available through pharmacies, corporate wellness programs, and Britton online storefronts.',tags:['memory','focus','ginkgo']},
{id:'napease',name:'Napease Menthol Patch',division:'Digital OTC',category:'Pain Relief',image:'napease 1.webp',imageAlt:'Napease menthol pain relief patch',summary:'Cooling menthol patch that soothes stiff neck, shoulder, and back discomfort.',benefits:['Provides long-lasting cooling comfort for muscle and joint aches.','Non-greasy patch adheres securely yet removes cleanly.'],directions:['Clean and dry the affected area before applying the patch.','Use up to three patches per day and avoid placing on broken skin.'],availability:'Available in supermarkets, convenience stores, and nationwide pharmacy partners.',tags:['patch','muscle pain','menthol']},
{id:'primovit',name:'Primovit Capsule',division:'Digital OTC',category:'Women’s Health',image:'primovit capsule.webp',imageAlt:'Primovit women’s multivitamin',summary:'Daily multivitamin for women that supports energy, immunity, and overall wellness.',benefits:['Delivers essential vitamins and minerals for women with active routines.','Helps bridge nutritional gaps from demanding work or family schedules.'],directions:['Take one capsule daily with breakfast or as recommended by your healthcare provider.','Consult a physician before use if pregnant, breastfeeding, or taking other supplements.'],availability:'Available in major drugstores, supermarkets, and Britton-authorized online stores.',tags:['women','multivitamin','energy']},
{id:'aminoral',name:'Aminoral',division:'Division 1 - Nephro',category:'Renal Nutrition',image:'aminoral 1.webp',imageAlt:'Aminoral renal nutrition tablets',summary:'Keto-analog and amino acid tablet that supports protein-restricted kidney diets.',benefits:['Helps maintain nutritional status for CKD and dialysis patients.','Complements low-protein diets to delay disease progression.'],directions:['Take tablets with meals exactly as prescribed by your nephrologist.','Keep regular lab monitoring to track kidney function and electrolytes.'],availability:'Available via Britton nephrology representatives, dialysis centers, and hospital pharmacies.',tags:['kidney','ckd','nutrition']},
{id:'nuparin-5000',name:'Nuparin 5000 IU/mL',division:'Division 1 – Nephro',category:'Anticoagulant',image:'NUPARIN 5000.webp',imageAlt:'Nuparin 5000 heparin vial',summary:'Low molecular weight heparin used for dialysis anticoagulation and thrombosis prevention.',benefits:['Delivers reliable anticoagulation during dialysis sessions.','Supported by Britton clinical training for hospital partners.'],directions:['Administer only under licensed medical supervision following facility protocols.','Monitor coagulation parameters and watch for signs of bleeding.'],availability:'Supplied exclusively to accredited hospitals, dialysis centers, and government tenders.',tags:['heparin','dialysis','anticoagulant']},
{id:'bagabrit',name:'Bagabrit',division:'Division 1 – Neuro',category:'Neuropathic Pain',image:'BAGABRIT.webp',imageAlt:'Bagabrit gabapentin capsules',summary:'Gabapentin capsule prescribed for neuropathic pain and seizure control.',benefits:['Eases nerve pain from diabetic neuropathy and post-herpetic neuralgia.','Available in strengths suited for individualized titration.'],directions:['Take exactly as directed by your neurologist; do not stop abruptly.','Report unusual mood or neurological changes immediately.'],availability:'Distributed to neurologists, specialty clinics, and pharmacies serving prescription patients.',tags:['nerve pain','gabapentin','rx']},
{id:'bristat',name:'Bristat',division:'Division 1 – Ortho Rheuma',category:'Anti-inflammatory',image:'BRISTAT.webp',imageAlt:'Bristat anti-inflammatory tablets',summary:'NSAID tablet that relieves musculoskeletal pain and inflammation.',benefits:['Targets joint and muscle pain for better mobility.','Trusted option for orthopedic and rheumatology specialists.'],directions:['Take with food exactly as prescribed to reduce gastric upset.','Avoid combining with other NSAIDs unless cleared by your physician.'],availability:'Available in orthopedic clinics, rehabilitation centers, and community pharmacies with Rx counters.',tags:['pain','nsaid','orthopedic']},
{id:'folisure',name:'Folisure',division:'Division 1 – Pedia / Derma / OB',category:'Prenatal Care',image:'FOLISURE.webp',imageAlt:'Folisure folic acid supplement',summary:'Folic acid tablet that supports healthy pregnancy and neural tube development.',benefits:['Provides 400 mcg folic acid for women planning or expecting pregnancy.','Supports red blood cell formation and maternal wellness.'],directions:['Take one tablet daily at least a month before conception and throughout pregnancy.',"Follow your OB-GYN's advice on diet, supplements, and prenatal checkups."],availability:'Carried by OB-GYN clinics, maternity hospitals, and nationwide pharmacy chains.',tags:['folic acid','prenatal','women']},
{id:'fenogal',name:'Fenogal',division:'Division 2 - Cardio',category:'Lipid Management',image:'FENOGAL 1.webp',imageAlt:'Fenogal fenofibrate pack',summary:'Fenofibrate capsule that helps lower triglycerides and improve cholesterol profile.',benefits:['Adjunct to diet and exercise for mixed dyslipidemia.','Available in strengths to tailor cardiovascular therapy.'],directions:['Take once daily with meals as directed by your cardiologist.','Schedule regular lipid tests and report unexplained muscle pain.'],availability:'Supplied to cardiology clinics, hospitals, and major retail pharmacies.',tags:['cholesterol','fenofibrate','cardio']},
{id:'vaptor',name:'Vaptor',division:'Division 2 - Cardio',category:'Lipid Management',image:'VAPTOR 1.webp',imageAlt:'Vaptor atorvastatin tablets',summary:'Atorvastatin tablet prescribed to lower LDL cholesterol and protect the heart.',benefits:['Helps patients reach LDL targets alongside diet and exercise.','Supported by extensive clinical data for cardiovascular risk reduction.'],directions:['Take once daily in the evening or exactly as directed by your cardiologist.','Report persistent muscle pain or dark urine to your doctor immediately.'],availability:'Available at cardiology clinics, tertiary hospitals, and nationwide pharmacy partners.',tags:['atorvastatin','cholesterol','statin']},
{id:'telchor',name:'Telchor',division:'Division 2 - Cardio',category:'Hypertension',image:'TELCHOR 1.webp',imageAlt:'Telchor telmisartan tablet',summary:'Telmisartan tablet that offers 24-hour blood pressure control and organ protection.',benefits:['Supports heart and kidney health for hypertensive patients.','Once-daily dosing encourages long-term adherence.'],directions:['Take one tablet daily at the same time or as prescribed by your physician.','Monitor blood pressure regularly and attend scheduled follow-ups.'],availability:'Supplied to cardiologists, hospitals, and drugstores that handle chronic-care prescriptions.',tags:['telmisartan','hypertension','cardio']},
{id:'telmal',name:'Telmal Series',division:'Division 2 - Cardio',category:'Combination Therapy',image:'TELMAL GROUP.webp',imageAlt:'Telmal combination antihypertensives',summary:'Fixed-dose telmisartan combinations that simplify blood pressure control.',benefits:['Delivers synergistic blood pressure reduction with once-daily dosing.','Multiple strengths to match physician treatment plans.'],directions:['Take exactly as prescribed and monitor blood pressure at home.','Maintain lifestyle measures such as low-sodium meals and daily activity.'],availability:'Distributed to cardiology clinics, hospitals, and pharmacies offering chronic care medicines.',tags:['hypertension','telmisartan','combination']},
{id:'canem',name:'Canem',division:'Division 2 – Gastro / IDS / IM / GP',category:'Antibacterial',image:'CANEM.webp',imageAlt:'Canem carbapenem vial',summary:'Hospital-use carbapenem antibiotic reserved for serious gram-negative infections.',benefits:['Covers a broad spectrum of resistant pathogens.','Supported by Britton cold-chain and institutional training programs.'],directions:['Prepare and infuse intravenously under strict hospital protocols.','Adjust dosing based on renal function and culture results.'],availability:'Restricted to accredited hospitals and institutional partners served by Britton.',tags:['antibiotic','carbapenem','hospital']},
{id:'domplux',name:'Domplux',division:'Division 2 – Gastro / IDS / IM / GP',category:'Gastrointestinal',image:'DOMPLUX 1.webp',imageAlt:'Domplux domperidone tablets',summary:'Domperidone tablet that relieves nausea, vomiting, and gastric motility discomfort.',benefits:['Improves gastric emptying to ease bloating and fullness.','Pairs well with acid suppressants for functional dyspepsia.'],directions:['Take before meals exactly as prescribed and follow duration limits.','Inform your doctor about any existing heart rhythm issues or medications.'],availability:'Available in gastroenterology clinics, hospitals, and community pharmacies with prescription counters.',tags:['domperidone','nausea','motility']},
{id:'zenalb',name:'Zenalb',division:'Division 2 – Gastro / IDS / IM / GP',category:'Plasma Volume Expander',image:'ZENALB 1.webp',imageAlt:'Zenalb human albumin bottle',summary:'Human albumin solution used in critical care to restore or maintain circulating volume.',benefits:['Provides dependable plasma expansion for ICU and surgical patients.','Pharmaceutical-grade albumin with rigorous quality controls.'],directions:['Administer intravenously under physician supervision while monitoring vitals.','Store under recommended conditions and use within the stated timeframe after opening.'],availability:'Supplied to intensive care units, surgical centers, and government hospitals via Britton critical care teams.',tags:['albumin','icu','critical care']}
];
const ITEMS_PER_PAGE=8;
const $=id=>document.getElementById(id);
const search=$('productSearch');
if(!search)return;
const divisionFilter=$('divisionFilter'),categoryFilter=$('categoryFilter'),results=$('productResults'),summaryEl=$('catalogSummary'),empty=$('catalogEmpty'),prev=$('prevPage'),next=$('nextPage'),pages=$('paginationPages');
const modal=$('productModal'),modalImg=$('productModalImage'),modalTitle=$('productModalTitle'),modalTags=$('productModalTags'),modalSummary=$('productModalSummary'),modalBenefits=$('productModalBenefits'),modalDirections=$('productModalDirections'),modalAvailability=$('productModalAvailability'),modalClose=$('productModalClose');
let filtered=[...PRODUCTS].sort(sortByName),page=1,lastFocus=null;
initFilters();
attach();
render();
function initFilters(){const divisions=[...new Set(PRODUCTS.map(p=>p.division))].sort();divisions.forEach(d=>{const opt=document.createElement('option');opt.value=d;opt.textContent=d;divisionFilter.appendChild(opt);});const categories=[...new Set(PRODUCTS.map(p=>p.category))].sort();categories.forEach(c=>{const opt=document.createElement('option');opt.value=c;opt.textContent=c;categoryFilter.appendChild(opt);});}
function attach(){search.addEventListener('input',debounce(()=>{page=1;filter();},200));divisionFilter.addEventListener('change',()=>{page=1;filter();});categoryFilter.addEventListener('change',()=>{page=1;filter();});prev.addEventListener('click',()=>{if(page>1){page--;render();}});next.addEventListener('click',()=>{const total=Math.max(1,Math.ceil(filtered.length/ITEMS_PER_PAGE));if(page<total){page++;render();}});modalClose.addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target&&e.target.hasAttribute('data-modal-close'))closeModal();});}
function filter(){const query=search.value.trim().toLowerCase();const division=divisionFilter.value;const category=categoryFilter.value;filtered=PRODUCTS.filter(p=>{const matchDivision=division==='all'||p.division===division;const matchCategory=category==='all'||p.category===category;const haystack=(p.name+' '+p.summary+' '+p.division+' '+p.category+' '+(p.tags||[]).join(' ')).toLowerCase();const matchQuery=!query||haystack.includes(query);return matchDivision&&matchCategory&&matchQuery;}).sort(sortByName);render();}
function render(){results.innerHTML='';pages.innerHTML='';const total=filtered.length;const totalPages=Math.max(1,Math.ceil(total/ITEMS_PER_PAGE));if(page>totalPages)page=totalPages;const start=(page-1)*ITEMS_PER_PAGE;const items=filtered.slice(start,start+ITEMS_PER_PAGE);if(total===0){empty.hidden=false;summaryEl.textContent='No products to display.';}else{empty.hidden=true;summaryEl.textContent=`Showing ${start+1}–${start+items.length} of ${total} products`;items.forEach(product=>results.appendChild(createCard(product)));}for(let i=1;i<=totalPages;i++){const btn=document.createElement('button');btn.type='button';btn.className='pagination-page'+(i===page?' is-active':'');btn.textContent=i;btn.disabled=i===page;btn.addEventListener('click',()=>{page=i;render();});pages.appendChild(btn);}prev.disabled=page===1;next.disabled=page===totalPages;}
function createCard(product){const card=document.createElement('article');card.className='product-card';const media=document.createElement('figure');media.className='product-card__media';const img=document.createElement('img');const imageName=encodeURI(product.image);img.src=`images/products/medium/${imageName}`;img.srcset=`images/products/small/${imageName} 576w, images/products/medium/${imageName} 1024w, images/products/large/${imageName} 1920w`;img.sizes='(min-width: 1200px) 25vw, (min-width: 768px) 33vw, 50vw';img.alt=product.imageAlt||product.name;img.loading='lazy';media.appendChild(img);const content=document.createElement('div');content.className='product-card__content';const meta=document.createElement('span');meta.className='product-card__meta';meta.textContent=`${product.division} • ${product.category}`;const title=document.createElement('h3');title.textContent=product.name;const summary=document.createElement('p');summary.className='product-card__summary';summary.textContent=product.summary;const action=document.createElement('button');action.type='button';action.className='product-card__action';action.textContent='View details';action.addEventListener('click',()=>openModal(product,action));content.append(meta,title,summary,action);card.append(media,content);return card;}
function openModal(product,trigger){lastFocus=trigger||document.activeElement;const imageName=encodeURI(product.image);modalImg.src=`images/products/large/${imageName}`;modalImg.alt=product.imageAlt||product.name;modalTitle.textContent=product.name;modalTags.textContent=`${product.division} • ${product.category}`;modalSummary.textContent=product.summary;fillList(modalBenefits,product.benefits);fillList(modalDirections,product.directions);modalAvailability.textContent=product.availability;modal.classList.add('is-visible');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');modalClose.focus();document.addEventListener('keydown',handleKeydown);}
function closeModal(){modal.classList.remove('is-visible');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');document.removeEventListener('keydown',handleKeydown);if(lastFocus&&typeof lastFocus.focus==='function')lastFocus.focus();}
function handleKeydown(e){if(e.key==='Escape')closeModal();}
function fillList(container,items){container.innerHTML='';(items||[]).forEach(text=>{const li=document.createElement('li');li.textContent=text;container.appendChild(li);});}
function sortByName(a,b){return a.name.localeCompare(b.name);}
function debounce(fn,delay){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn.apply(null,args),delay);};}
})();
